### ISSUE TITLE
Error while running Omniglot.py

### ISSUE THREAD

**Issue by i--storm** [hmishra2250/NTM-One-Shot-TF#1]
I receive such error while running

Traceback (most recent call last):
  File "/root/tensorflow/anomaly-detector/NTM-One-Shot-TF/Omniglot.py", line 112, in <module>
    omniglot()
  File "/root/tensorflow/anomaly-detector/NTM-One-Shot-TF/Omniglot.py", line 85, in omniglot
    for i, (batch_input, batch_output) in generator:
  File "/root/tensorflow/anomaly-detector/NTM-One-Shot-TF/MANN/Utils/Generator.py", line 36, in next
    return (self.num_iter - 1), self.sample(self.nb_samples)
  File "/root/tensorflow/anomaly-detector/NTM-One-Shot-TF/MANN/Utils/Generator.py", line 56, in sample
    for (filename, angle, shift) in zip(image_files, angles, shifts)], dtype=np.float32)
  File "/root/tensorflow/anomaly-detector/NTM-One-Shot-TF/MANN/Utils/Images.py", line 29, in load_transform
    original = imread(image_path, flatten=True)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2251, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 21] Is a directory: './data/omniglot/images_background/Japanese_(katakana)/character45'

Last two dirs in path may vary

**Comment by i--storm** [comment]
Found solution
images_background.zip contains folder images_background with language folders
language filders should be unpacked directly into ./data/omniglot without images_background folder
