### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by yangyu12** [hmishra2250/NTM-One-Shot-TF#2]
Hi, I'am exploring your code recently, I've encountered a problem when I try to run `python Omniglot.py`. 
System: Ubuntu 16.04
tensroflow version: 1.1.0-rc2
cuda 8.0
python: 2.7 

The error information is as following, could you please help me to find out the solution?
```
python Omniglot.py
Traceback (most recent call last):
  File "Omniglot.py", line 112, in <module>
    omniglot()
  File "Omniglot.py", line 31, in omniglot
    output_var, output_var_flatten, params = memory_augmented_neural_network(input_ph, target_ph, batch_size=batch_size, nb_class=nb_class, memory_shape=memory_shape, controller_size=controller_size, input_size=input_size, nb_reads=nb_reads)
  File "/data/yangyu/workspace/MANN/MANN/Model.py", line 33, in memory_augmented_neural_network
    W_key = tf.get_variable('W_key', shape=shape,initializer=tf.random_uniform_initializer(-1*high, high))
  File "/data/yangyu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/data/yangyu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/data/yangyu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/data/yangyu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 303, in _true_getter
    is_scalar = shape is not None and not shape

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by gautam1858** [comment]
Having the same error for me in OSx

**Comment by yangyu12** [comment]
Hi,@gautam1858 
I noted that the author has mentioned in README

> Written for Tensorflow v0.12. Yet to add support for Tensorflow v1*.

I guess the reason is that I use tf v1*, I don't know whether is it the case for you.

**Comment by hmishra2250** [comment]
>I guess the reason is that I use tf v1*, I don't know whether is it the case for you.

Bingo. There you go. That's the issue.
I too had faced it when I updated my Tensorflow. Anyways I have migrated the code base for Tensorflow 1.1. Do merge your codebases accordingly!
