### ISSUE TITLE
IOError: [Errno 21] Is a directory: 

### ISSUE THREAD

**Issue by fanyuzeng** [hmishra2250/NTM-One-Shot-TF#7]
When I run this code.The terminal appears following:
/usr/bin/python2.7 /home/cr/PycharmProjects/NTM-One-Shot-TF-master/Omniglot.py
Shapes Recieved in Update: V, dim, val are ==>  [64, 128] [64] [64]
Shapes Recieved in Body of Update: v, d2, chg are ==>  [128] [] []
wlu_tm1 :  [16, 4]
Shapes Recieved in Update: V, dim, val are ==>  [16, 128, 40] [16] [16, 40]
Shapes Recieved in Body of Update: v, d2, chg are ==>  [128, 40] [] [40]
Compiling the Model
Output, Target shapes:  [16, 50, 5] [16, 50, 5]
Done
Traceback (most recent call last):
  File "/home/cr/PycharmProjects/NTM-One-Shot-TF-master/Omniglot.py", line 113, in <module>
    omniglot()
  File "/home/cr/PycharmProjects/NTM-One-Shot-TF-master/Omniglot.py", line 87, in omniglot
    for i, (batch_input, batch_output) in generator:
  File "/home/cr/PycharmProjects/NTM-One-Shot-TF-master/MANN/Utils/Generator.py", line 36, in next
    return (self.num_iter - 1), self.sample(self.nb_samples)
  File "/home/cr/PycharmProjects/NTM-One-Shot-TF-master/MANN/Utils/Generator.py", line 56, in sample
    for (filename, angle, shift) in zip(image_files, angles, shifts)], dtype=np.float32)
  File "/home/cr/PycharmProjects/NTM-One-Shot-TF-master/MANN/Utils/Images.py", line 29, in load_transform
    original = imread(image_path, flatten=True)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1996, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 21] Is a directory: './data/omniglot/images_background/Blackfoot_(Canadian_Aboriginal_Syllabics)/character11'
Training the model

Process finished with exit code 1

How to handle this problem？

**Comment by fanyuzeng** [comment]
I change './data/omniglot' to './data/omniglot/images_background', it work.
